Sync all local changes
Signed-off-by: David Sterba <dave@jikos.cz>

diff --git a/run-list b/run-list
--- a/run-list
+++ b/run-list
@@ -1,41 +1,41 @@
 #!/bin/sh
 
-test -d mmtests || { echo "no mmtests"; exit 1; }
-test -z "$1" && { echo "no config list given"; exit 1; }
+test -d mmtests || { echo "ERROR: no mmtests dir found"; exit 1; }
+test -z "$1" && { echo "ERROR: no config list given"; exit 1; }
 
 here=`pwd`
 if [ -f 'config-tag' ]; then
-	echo "Found tag file, using it"
+	echo "INFO: Found tag file, using it"
 	tag=`cat config-tag | tr -d '\t\n '`
 else
-	echo "Generating tag from kernel version"
+	echo "INFO: Generating tag from kernel version"
 	tag=`uname -r | sed -e 's/-.*$//'`
 fi
 echo "TAG: $tag"
 
 hostconf="$here/config-m-`hostname`"
-fsconf="$here/config-btrfs"
+fsconf="$here/config-base"
 mnt="$here/mmtests/work/testdisk"
 
 cd mmtests
 for config in `cat "$here/$1"`; do
-	echo "Execute mmtests and config $config"
+	echo "INFO: Execute mmtests and config $config"
 
 	if findmnt "$mnt"; then
-		echo "Found that $mnt is still mounted, fix it or press Enter to continue"
+		echo "WARNING: Found that $mnt is still mounted, fix it or press Enter to continue"
 		read
 	fi
 
 	conf="$here/$config"
 	if ! [ -f "$conf" ]; then
 		if [ -f "$here/mmtests/configs/$config" ]; then
-			echo "Using config inside mmtests"
+			echo "INFO: Using config inside mmtests"
 			conf="$here/mmtests/configs/$config"
 		else
-			echo "Warning: config not found"
+			echo "WARNING: config $conf not found"
 		fi
 	else
-		echo "Using local config file $conf"
+		echo "INFO: Using local config file $conf"
 	fi
 
 	./run-mmtests.sh -c "$fsconf" -c "$hostconf" -c "$conf" "$tag"
diff --git a/run-mkfs b/run-mkfs
--- a/run-mkfs
+++ b/run-mkfs
@@ -1,8 +1,10 @@
 #!/bin/sh
+# Create filesystem from config settings (type, flags, device)
+# Usage: $0 [configs...]
 
 here=`pwd`
 hostconf="$here/config-m-`hostname`"
-fsconf="$here/config-btrfs"
+fsconf="$here/config-base"
 
 source "$hostconf"
 source "$fsconf"
@@ -13,13 +15,13 @@ for arg in "$@"; do
 	source "$p"
 done
 
-[ -z "$TESTDISK_FILESYSTEM" ] && { echo "no filesystem defined"; exit 1; }
-[ -z "$TESTDISK_PARTITION" ] && { echo "no partition defined"; exit 1; }
+[ -z "$TESTDISK_FILESYSTEM" ] && { echo "ERROR: no filesystem defined"; exit 1; }
+[ -z "$TESTDISK_PARTITION" ] && { echo "ERROR: no partition defined"; exit 1; }
 
 if findmnt "$TESTDISK_PARTITION"; then
-	echo "Found that $TESTDISK_PARTITION is still mounted, fix it manually"
+	echo "ERROR: Found that $TESTDISK_PARTITION is still mounted, fix it manually"
 	exit 1
 fi
 
-echo COMMAND: mkfs."$TESTDISK_FILESYSTEM" $TESTDISK_MKFS_PARAM $TESTDISK_PARTITION $TESTDISK_MKFS_PARAM_SUFFIX
+echo RUN: mkfs."$TESTDISK_FILESYSTEM" $TESTDISK_MKFS_PARAM $TESTDISK_PARTITION $TESTDISK_MKFS_PARAM_SUFFIX
 mkfs."$TESTDISK_FILESYSTEM" $TESTDISK_MKFS_PARAM $TESTDISK_PARTITION $TESTDISK_MKFS_PARAM_SUFFIX
